version: "3"
services:

  editor:
    build: ./app
    ports:
      - 3006:5000
  api:
    build: ./api
    ports:
      - 3001:3000
    volumes:
      - ~/pacpac/data/media:/api/public
  db:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ~/pacpac/data/database:/data