const EventTypes = {

    CLICK : 'CLICK',
    CHANGE_STATE_EVENT: 'CHANGE_STATE_EVENT',
    DETECTS_MOTION: 'DETECTS_MOTION',
    DETECTS_SMOKE: 'DETECTS_SMOKE',
    CHANGE_COLOR_EVENT: 'CHANGE_COLOR_EVENT',
    CHANGE_TEMPERATURE_EVENT: 'CHANGE_TEMPERATURE_EVENT',
    CHANGE_VOLUME_EVENT: 'CHANGE_VOLUME_EVENT',
    CHANGE_SHUTTER_EVENT: 'CHANGE_SHUTTER_EVENT',
    OPEN_CLOSE_DOOR_EVENT: 'OPEN_CLOSE_DOOR_EVENT',
    CHANGE_VALUE_EVENT: 'CHANGE_VALUE_EVENT',
    CHANGE_STATE_SENSOR_EVENT: 'CHANGE_STATE_SENSOR_EVENT',

};

export default EventTypes;
