const Operators = {
    EQUAL : 'EQUAL',
    EQUAL_OPEN : 'EQUAL_OPEN',
    NOT_EQUAL_OPEN : 'NOT_EQUAL_OPEN',
    EQUAL_LOCK : 'EQUAL_LOCK',
    NOT_EQUAL_LOCK : 'NOT_EQUAL_LOCK',
    EQUAL_NUM: 'EQUAL_NUM',
    NOT_EQUAL : 'NOT_EQUAL',
    NOT_EQUAL_NUM: 'NOT_EQUAL_NUM',
    LESS_THAN : 'LESS_THAN',
    LESS_EQUAL : 'LESS_EQUAL',
    GREATER_THAN : 'GREATER_THAN',
    GREATER_EQUAL : 'GREATER_EQUAL',
    TEMP_EQUAL_NUM: 'TEMP_EQUAL_NUM',
    TEMP_NOT_EQUAL_NUM : 'TEMP_NOT_EQUAL_NUM',
    TEMP_LESS_THAN : 'TEMP_LESS_THAN',
    TEMP_LESS_EQUAL : 'TEMP_LESS_EQUAL',
    TEMP_GREATER_THAN : 'TEMP_GREATER_THAN',
    TEMP_GREATER_EQUAL : 'TEMP_GREATER_EQUAL',
    VOLUME_EQUAL_NUM: 'VOLUME_EQUAL_NUM',
    VOLUME_NOT_EQUAL_NUM : 'VOLUME_NOT_EQUAL_NUM',
    VOLUME_LESS_THAN : 'VOLUME_LESS_THAN',
    VOLUME_LESS_EQUAL : 'VOLUME_LESS_EQUAL',
    VOLUME_GREATER_THAN : 'VOLUME_GREATER_THAN',
    VOLUME_GREATER_EQUAL : 'VOLUME_GREATER_EQUAL',
    SHUTTER_EQUAL_NUM: 'SHUTTER_EQUAL_NUM',
    SHUTTER_NOT_EQUAL_NUM : 'SHUTTER_NOT_EQUAL_NUM',
    SHUTTER_LESS_THAN : 'SHUTTER_LESS_THAN',
    SHUTTER_LESS_EQUAL : 'SHUTTER_LESS_EQUAL',
    SHUTTER_GREATER_THAN : 'SHUTTER_GREATER_THAN',
    SHUTTER_GREATER_EQUAL : 'SHUTTER_GREATER_EQUAL',
    IN : 'IN'
};

const SuperOperators = {
    AND : 'AND',
    OR : 'OR',
    NOT : 'NOT',
};

export {
    Operators, SuperOperators
};
