import Values from "./Values";
import InteractiveObjectsTypes from "../interactives/InteractiveObjectsTypes";
import Immutable from "immutable";

const RuleActionTypes = {

    CHANGE_BACKGROUND: 'CHANGE_BACKGROUND',
    CHANGE_VALUE_EVENT: 'CHANGE_VALUE_EVENT',
    CHANGE_STATE_EVENT: 'CHANGE_STATE_EVENT',
    CHANGE_COLOR_EVENT: 'CHANGE_COLOR_EVENT',
    CHANGE_TEMPERATURE_EVENT: 'CHANGE_TEMPERATURE_EVENT',
    CHANGE_SHUTTER_EVENT: 'CHANGE_SHUTTER_EVENT',
    CHANGE_VOLUME_EVENT: 'CHANGE_VOLUME_EVENT',
    OPEN_CLOSE_DOOR_EVENT: 'OPEN_CLOSE_DOOR_EVENT',
    CHANGE_STATE: 'CHANGE_STATE',
    CHANGE_VISIBILITY : 'CHANGE_VISIBILITY',
    COLLECT_KEY: 'COLLECT_KEY',
    CLICK: 'CLICK',
    DECREASE_STEP: 'DECREASE_STEP',
    INCREASE_STEP: 'INCREASE_STEP',
    INCREASE: 'INCREASE',
    IS: 'IS',
    LOOK_AT: 'LOOK_AT',
    OFF : 'OFF',
    ON : 'ON',
    PLAY: 'PLAY',
    PLAY_LOOP: 'PLAY_LOOP',
    STOP: 'STOP',
    TRANSITION : 'TRANSITION',
    UNLOCK_LOCK: 'UNLOCK_LOCK',
    UNLOCK_LOCK_DOOR: 'UNLOCK_LOCK_DOOR',
    CHANGE_COLOR: 'CHANGE_COLOR',
    CHANGE_TEMPERATURE: 'CHANGE_TEMPERATURE',
    CHANGE_VOLUME: 'CHANGE_VOLUME',
    CHANGE_SHUTTER: 'CHANGE_SHUTTER',
    DETECTS_MOTION: 'DETECTS_MOTION',
    DETECTS_SMOKE: 'DETECTS_SMOKE',

};

export default RuleActionTypes;
