const InteractiveObjectsTypes = {

    BUTTON : 'BUTTON',
    COUNTER : 'COUNTER',
    CUMULABLE : 'CUMULABLE',
    KEY : 'KEY',
    KEYPAD : 'KEYPAD',
    LOCK : 'LOCK',
    PLAYER : 'PLAYER',
    POINT_OF_INTEREST: 'POINT_OF_INTEREST',
    SELECTOR : 'SELECTOR',
    SWITCH : 'SWITCH',
    TIMER : 'TIMER',
    TRANSITION : 'TRANSITION',

    // - IoT Devices
    BLIND : 'BLIND',
    DOOR: 'DOOR',
    AIR_CONDITIONER: 'AIR_CONDITIONER',
    LIGHT : 'LIGHT',
    MOTION_DETECTOR: 'MOTION_DETECTOR',
    POWER_OUTLET: 'POWER_OUTLET',
    DSWITCH: 'POWER_SWITCH',
    SENSOR: 'SENSOR',
    SIREN: 'SIREN',
    SMOKE_DETECTOR: 'SMOKE_DETECTOR',
    SPEAKER: 'SPEAKER',

};

export default InteractiveObjectsTypes;
