const ActionTypes = {

    //EDITOR MODES

    PLAY_MODE_ON : 'PLAY_MODE_ON',
    EDIT_MODE_ON : 'EDIT_MODE_ON',
    GEOMETRY_MODE_ON: 'GEOMETRY_MODE_ON',

    //SCENES

    CLICK_SCENE : 'CLICK_SCENE',
    LOAD_ALL_SCENES : 'LOAD_ALL_SCENES',
    RECEIVE_SCENE : 'RECEIVE_SCENE',
    REMOVE_SCENE: 'REMOVE_SCENE',
    REMOVE_ALL_SCENES: 'REMOVE_ALL_SCENE',
    UPDATE_CURRENT_SCENE : 'UPDATE_CURRENT_SCENE',
    UPDATE_SCENE : 'UPDATE_SCENE',

    //TAGS

    ADD_NEW_TAG : 'ADD_NEW_TAG',
    LOAD_ALL_TAGS : 'LOAD_ALL_TAGS',

    // INTERACTIVE OBJECTS

    ADD_NEW_OBJECT : 'ADD_NEW_OBJECT',
    LOAD_ALL_OBJECTS : 'LOAD_ALL_OBJECTS',
    SELECT_ALL_OBJECTS : 'SELECT_ALL_OBJECTS',
    UPDATE_CURRENT_OBJECT : 'UPDATE_CURRENT_OBJECT',
    UPDATE_OBJECT : 'UPDATE_OBJECT',
    LOAD_OBJECT: 'LOAD_OBJECT',
    REMOVE_OBJECT: 'REMOVE_OBJECT',
    OBJECTS_FILTER: 'OBJECTS_FILTER',

    //RULES

    ADD_NEW_RULE : 'ADD_NEW_RULE',
    REMOVE_RULE : 'REMOVE_RULE',

    //OTHER
    ON_PICTURE_DROP : 'ON_PICTURE_DROP',
    UPDATE_DATALIST : 'UPDATE_DATALIST',
};

export default ActionTypes;