const ActionTypes = {

    RESET: 'RESET',

    //EDITOR

    EDIT_MODE_ON : 'EDIT_MODE_ON',
    GAME_SELECTION_MODE_ON : 'GAME_SELECTION_MODE_ON' ,
    GEOMETRY_MODE_ON : 'GEOMETRY_MODE_ON',
    NAVBAR_SELECTION : 'NAVBAR_SELECTION',
    PLAY_MODE_ON : 'PLAY_MODE_ON',
    DEBUG_MODE_ON : 'DEBUG_MODE_ON',
    DEBUG_SAVES : 'DEBUG_SAVES',
    IS_IT_NEW: 'IS_IT_NEW',
    LOGIN_MODE_ON : 'LOGIN_MODE_ON',
    LEFTBAR_SELECTION : 'LEFTBAR_SELECTION',
    LOOP_CHECK : 'LOOP_CHECK',
    FILE_MANAGER_MODE_ON : 'FILE_MANAGER_MODE_ON',
    RIGHTBAR_SELECTION : 'RIGHTBAR_SELECTION',
    DROPDOWN_SCENES_ORDER : 'DROPDOWN_SCENES_ORDER',
    DROPDOWN_TAGS_NEW_SCENE : 'DROPDOWN_TAGS_NEW_SCENE',
    DROPDOWN_TAGS_RIGHTBAR : 'DROPDOWN_TAGS_RIGHTBAR',
    EDITOR_EXPANDED: 'EDITOR_EXPANDED',
    SELECT_TAG_NEW_SCENE : 'SELECT_TAG_NEW_SCENE',
    SELECT_AUDIO_FILE: 'SELECT_AUDIO_FILE',
    SELECT_FILE : 'SELECT_FILE',
    SELECT_MEDIA_TO_EDIT : 'SELECT_MEDIA_TO_EDIT',
    SELECT_AUDIO_TO_EDIT : 'SELECT_AUDIO_TO_EDIT',
    SELECT_SCENE_SPATIAL_AUDIO: 'SELECT_SCENE_SPATIAL_AUDIO',
    SET_HOME_SCENE: 'SET_HOME_SCENE',
    SET_GAME_TITLE: 'SET_GAME_TITLE',
    SOUND_ACTIVE_FORM_CHECK: 'SOUND_ACTIVE_FORM_CHECK',
    SOUND_ACTIVE_RIGHTBAR_CHECK: 'SOUND_ACTIVE_RIGHTBAR_CHECK',
    AUDIO_FORM_STATUS : 'AUDIO_FORM_STATUS',
    AUDIO_SPATIAL_OPTION: 'AUDIO_SPATIAL_OPTION',
    AUDIO_POSITIONING: 'AUDIO_POSITIONING',
    UPDATE_AUDIO_FILTER: 'UPDATE_AUDIO_FILTER',
    UPDATE_TAG_FILTER: 'UPDATE_TAG_FILTER',
    UPDATE_OBJECT_NAME_RIGHTBAR: 'UPDATE_OBJECT_NAME_RIGHTBAR',
    UPDATE_OBJECTS_NAME_FILTER: 'UPDATE_OBJECTS_NAME_FILTER',
    UPDATE_OBJECTS_TYPE_FILTER : 'UPDATE_OBJECTS_TYPE_FILTER',
    UPDATE_SCENE_NAME_FILTER : 'UPDATE_SCENE_NAME_FILTER',
    UPDATE_SCENE_NAME_RIGHTBAR: 'UPDATE_SCENE_NAME_RIGHTBAR',
    UPDATE_SCENE_OPTIONS: 'UPDATE_SCENE_OPTIONS',
    NEW_AUDIO_NAME_TYPED: 'NEW_AUDIO_NAME_TYPED',
    NEW_SCENE_NAME_TYPED: 'NEW_SCENE_NAME_TYPED',
	STORY_EDITOR_MODE_ON: 'STORY_EDITOR_MODE_ON', //STORY EDITOR MODE
	
    //SCENES

    CLICK_SCENE : 'CLICK_SCENE',
    LOAD_ALL_SCENES : 'LOAD_ALL_SCENES',
    RECEIVE_SCENE : 'RECEIVE_SCENE',
    REMOVE_SCENE : 'REMOVE_SCENE',
    REMOVE_ALL_SCENES : 'REMOVE_ALL_SCENES',
    SORT_SCENES : 'SORT_SCENES',
    UPDATE_CURRENT_SCENE : 'UPDATE_CURRENT_SCENE',
    UPDATE_SCENE : 'UPDATE_SCENE',
    UPDATE_SCENE_NAME : 'UPDATE_SCENE_NAME',

    // TAGS

    ADD_NEW_TAG : 'ADD_NEW_TAG',
    RECEIVE_TAG : 'RECEIVE_TAG',
    REMOVE_TAG : 'REMOVE_TAG',
    UPDATE_TAG: 'UPDATE_TAG',

    // INTERACTIVE OBJECTS

    ADD_NEW_OBJECT : 'ADD_NEW_OBJECT',
    LOAD_ALL_OBJECTS : 'LOAD_ALL_OBJECTS',
    RECEIVE_OBJECT : 'RECEIVE_OBJECT',
    REMOVE_OBJECT : 'REMOVE_OBJECT',
    SELECT_ALL_OBJECTS : 'SELECT_ALL_OBJECTS',
    UPDATE_CURRENT_OBJECT : 'UPDATE_CURRENT_OBJECT',
    UPDATE_OBJECT : 'UPDATE_OBJECT',
    UPDATE_VERTICES : 'UPDATE_VERTICES',

    // RULES

    ADD_NEW_RULE : 'ADD_NEW_RULE',
    RECEIVE_RULE : 'RECEIVE_RULE',
    REMOVE_RULE : 'REMOVE_RULE',
    SET_MENTION_TYPE : 'SET_MENTION_TYPE',
    UPDATE_RULE : 'UPDATE_RULE',
    UPDATE_RULE_EDITOR_CONTENT: 'UPDATE_RULE_EDITOR_CONTENT',
    UPDATE_RULE_EDITOR_RAW: 'UPDATE_RULE_EDITOR_RAW',
    UPDATE_RULE_EDITOR_STATE: 'UPDATE_RULE_EDITOR_STATE',
    UPDATE_SUGGESTION: 'UPDATE_SUGGESTION',
    // [davide] gestione dello stato dell'editor
    EUD_SHOW_COMPLETIONS: 'EUD_SHOW_COMPLETION',
    EUD_SAVE_ORIGINAL_OBJECT: 'EUD_SAVE_ORIGINAL_OBJECT',

    // AUDIO

    ADD_NEW_GLOBAL_AUDIO : 'ADD_NEW_GLOBAL_AUDIO',
    ADD_NEW_SPATIAL_AUDIO : 'ADD_NEW_SPATIAL_AUDIO',
    RECEIVE_GLOBAL_AUDIO: 'RECEIVE_GLOBAL_AUDIO',
    RECEIVE_SPATIAL_AUDIO: 'RECEIVE_SPATIAL_AUDIO',
    REMOVE_GLOBAL_AUDIO : 'REMOVE_GLOBAL_AUDIO',
    REMOVE_SPATIAL_AUDIO : 'REMOVE_SPATIAL_AUDIO',
    UPDATE_AUDIO: 'UPDATE_AUDIO',

    // MEDIA

    LOAD_ALL_ASSETS : 'LOAD_ALL_ASSETS',

    // OTHER

    ON_PICTURE_DROP : 'ON_PICTURE_DROP',
    RECEIVE_USER : 'RECEIVE_USER',
    UPDATE_DATALIST : 'UPDATE_DATALIST',
	
	
	//STORY EDITOR
	LOAD_ALL_COLLECTIONS: 'LOAD_ALL_COLLECTIONS',
	RECEIVE_COLLECTION: 'RECEIVE_COLLECTION',
	UPDATE_COLLECTION: 'UPDATE_COLLECTION',
	REMOVE_COLLECTION: 'REMOVE_COLLECTION',
	
	RECEIVE_IMAGE: 'RECEIVE_IMAGE',
	UPDATE_IMAGE: 'UPDATE_IMAGE',
	REMOVE_IMAGE: 'REMOVE_IMAGE',
	
	RECEIVE_STORY: 'RECEIVE STORY',
	UPDATE_STORY: 'UPDATE_STORY',
	EDIT_STORY: 'EDIT_STORY',		
	REMOVE_STORY: 'REMOVE_STORY',	
	
	START_EDITING_STORY: 'START_EDITING_STORY',
	STOP_EDITING_STORY: 'STOP_EDITING_STORY',	
	
	ADD_FORM_IMAGE: 'ADD_FORM_IMAGE',
	RECEIVE_FORM_IMAGE: 'RECEIVE_FORM_IMAGE',
	UPDATE_FORM_IMAGE: 'UPDATE_FORM_IMAGE',
	UPDATE_FORM_IMAGE_NAME: 'UPDATE_FORM_IMAGE_NAME',
	REMOVE_FORM_IMAGE: 'REMOVE_FORM_IMAGE',
	RESET_FORM_IMAGE: 'RESET_FORM_IMAGE',
	
};

export default ActionTypes;