const RuleActionTypes = {

    CHANGE_BACKGROUND: 'CHANGE_BACKGROUND',
    CHANGE_STATE: 'CHANGE_STATE',
    CHANGE_VISIBILITY : 'CHANGE_VISIBILITY',
    COLLECT_KEY: 'COLLECT_KEY',
    CLICK: 'CLICK',
    FLIP_SWITCH: 'FLIP_SWITCH',
    OFF : 'OFF',
    ON : 'ON',
    PLAY_AUDIO: 'PLAY_AUDIO',
    STOP_AUDIO: 'STOP_AUDIO',
    TRANSITION : 'TRANSITION',
    UNLOCK_LOCK: 'UNLOCK_LOCK',
    VISIBLE: 'VISIBLE',
    INVISIBLE: 'INVISIBLE'
};

export default RuleActionTypes;